sudapp-master/config/routes.rb
Appl::Application.routes.draw do

  resources :images

  resources :amigos

  resources :video_skaters

  resources :photo_skaters do
    collection do
      get :new
    end
  end

  resources :photo_skaters do
    collection do
      get :new
    end
  end

  resources :video_posts do
    collection do
      get :new
    end
  end

  resources :photo_posts do
    collection do
      get :new
    end
  end

  resources :pedidos do
    collection do
      get :pedidos_user
    end
  end

  resources :videos do
    collection do
      get :inicio
    end
  end

  resources :contact

  resources :mailer

  resources :productos

  resources :tipo_productos

  resources :skaters

  resources :comment_posts

  resources :comment_photos

  resources :posts do
    collection do
      get :inicio
    end
  end

  resources :photos

  resources :albums

  devise_for :users

  resources :admin do
    collection do
      get :banner
      get :header
      get :footer
      get :activar_indumentaria
      get :desactivar_indumentaria
      get :crear_valor_indumentaria
      get :creare
      get :newsletterform
      post :contact_email_signed_in
      post :contact_email
    end
  end

  resources :welcome do
    collection do
      get :admin
    end
  end

  match "dispatch_email", to: "admin#dispatch_email", via: 'post'

  root 'welcome#admin'

  

end

sudapp-master/app/models/album.rb
class Album < ActiveRecord::Base

	has_many :photos, :dependent => :destroy
	
	validates_presence_of :album_title

end

sudapp-master/app/models/amigo.rb
class Amigo < ActiveRecord::Base
end

sudapp-master/app/models/comment_photo.rb
class CommentPhoto < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

sudapp-master/app/models/comment_post.rb
class CommentPost < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

sudapp-master/app/models/image.rb
class Image < ActiveRecord::Base
	has_attached_file :photo
end

sudapp-master/app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :user
  belongs_to :producto
end

sudapp-master/app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :album
  
  has_many :comment_photos, :dependent => :destroy

  has_attached_file :photo


  validates_attachment_presence :photo
  validates_presence_of  :photo_title

  
end

sudapp-master/app/models/photo_post.rb
class PhotoPost < ActiveRecord::Base
  belongs_to :post
  has_attached_file :photo
end

sudapp-master/app/models/photo_skater.rb
class PhotoSkater < ActiveRecord::Base
  belongs_to :skater
  has_attached_file :photo
end

sudapp-master/app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comment_posts, :dependent => :destroy

	has_many :photo_posts, :dependent => :destroy

	has_many :video_posts, :dependent => :destroy

	has_attached_file :post_photo


    validates_attachment_presence :post_photo
    validates_presence_of  :post_title
    validates_presence_of :post_body

end

sudapp-master/app/models/producto.rb
class Producto < ActiveRecord::Base

  belongs_to :tipo_producto

  has_many :pedidos, :dependent => :destroy

  has_attached_file :foto_producto

  validates_presence_of :precio
  validates_presence_of :tipo_producto
  validates_presence_of :foto_producto
  validates_presence_of :talles_producto
  validates_presence_of :nombre_producto


end

sudapp-master/app/models/skater.rb
class Skater < ActiveRecord::Base

	has_many :photo_skaters, :dependent => :destroy

	has_many :video_skaters, :dependent => :destroy

	has_attached_file :skater_photo


    validates_attachment_presence :skater_photo
    validates_presence_of  :skater_name
    validates_presence_of :skater_body
    
end

sudapp-master/app/models/tipo_producto.rb
class TipoProducto < ActiveRecord::Base

    has_many :productos, :dependent => :destroy
    
	validates_presence_of :nombre_tipo_producto

end

sudapp-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :comment_photos, :dependent => :destroy

  has_many :comment_posts, :dependent => :destroy
  
  has_many :pedidos, :dependent => :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


        validates :username, :presence => true
        validates :username, :uniqueness => true
        validates :username, length: { maximum: 16 }
        validates :username, length: { minimum: 3 }
        validates :password, length: { maximum: 25 }
        validates :password, length: { minimum: 6 }


end

sudapp-master/app/models/video.rb
class Video < ActiveRecord::Base

validates_presence_of :video_title
validates_presence_of :video_url

end

sudapp-master/app/models/video_post.rb
class VideoPost < ActiveRecord::Base
  belongs_to :post
end

sudapp-master/app/models/video_skater.rb
class VideoSkater < ActiveRecord::Base
  belongs_to :skater
end

sudapp-master/app/helpers/admin_helper.rb
module AdminHelper
end

sudapp-master/app/helpers/albums_helper.rb
module AlbumsHelper
end

sudapp-master/app/helpers/posts_helper.rb
module PostsHelper
end

sudapp-master/app/views/admin/index.html.erb
<div class="large-12 columns">
<div class="large-6 columns">
<h1 style = "color:#B28D8D;">Administrador</h1>
<p></p>
<div class="my-div-bottom-dark"><%= link_to 'Crear una nueva nota', new_post_path, :class => "fuente-tres" %></div></br>
<div class="my-div-bottom-dark"><%= link_to 'Crear album', new_album_path, :class => "fuente-tres" %></div></br>
<div class="my-div-bottom-dark"><%= link_to 'Agregar una nueva foto', new_photo_path, :class => "fuente-tres" %></div></br>
<div class="my-div-bottom-dark"><%= link_to 'Agregar un nuevo video', new_video_path, :class => "fuente-tres" %></div></br>
<div class="my-div-bottom-dark"><%= link_to 'Crear un nuevo perfil', new_skater_path, :class => "fuente-tres" %></div></br>
<div class="my-div-bottom-dark"><%= link_to 'Agregar amigo', new_amigo_path, :class => "fuente-tres" %></div></br>
<div class="my-div-bottom-dark"><%= link_to 'Crear nueva categoria de producto', new_tipo_producto_path, :class => "fuente-tres" %></div></br>
<div class="my-div-bottom-dark"><%= link_to 'Agregar un nuevo producto', new_producto_path, :class => "fuente-tres" %></div></br>
<div class="my-div-bottom-dark"><%= link_to 'Enviar mail a los usuarios', {:controller=>'/admin', :action=>'newsletterform'}, :class => "fuente-tres" %></div></br>
<div class="my-div-bottom-dark"><%= link_to 'Revisar pedidos', pedidos_path, :class => "fuente-tres" %></div></br>



<% if ActivacionIndumentaria.first.activacion == false %>
<div class="my-div-bottom-dark"><%= link_to 'Activar indumentraria', :controller => '/admin', :action => 'activar_indumentaria', :class => "fuente-tres" %></div></br>
<% else %>
<div class="my-div-bottom-dark"><%= link_to 'Desactivar indumentraria', :controller => '/admin', :action => 'desactivar_indumentaria', :class => "fuente-tres" %></div></br>
<% end %>




<hr style="color:transparent; background-color:transparent">

</div>
<div class="large-6 columns">
	<!--<img src="/images/rana.gif" style="width:100%;"  />-->
</div>


</div>

sudapp-master/app/views/admin/newsletterform.html.erb
<h1 style = "color:#B28D8D;">Enviar email a los usuarios</h1>
<p style = "color:#B28D8D;">La siguiente información se enviará a todos los usuarios</p>

<%= form_tag :controller => '/admin', :action => 'dispatch_email' do %>

  <%= label_tag 'Asunto' %>
  <%= text_field_tag 'asunto' %>

  <%= label_tag 'Mensaje' %>
  <%= text_area_tag 'mensaje' %>
  <p></p>
  <%= submit_tag "Enviar" %>

<% end %>