sudapp-master/config/routes.rb
Appl::Application.routes.draw do

  resources :images

  resources :amigos

  resources :video_skaters

  resources :photo_skaters do
    collection do
      get :new
    end
  end

  resources :photo_skaters do
    collection do
      get :new
    end
  end

  resources :video_posts do
    collection do
      get :new
    end
  end

  resources :photo_posts do
    collection do
      get :new
    end
  end

  resources :pedidos do
    collection do
      get :pedidos_user
    end
  end

  resources :videos do
    collection do
      get :inicio
    end
  end

  resources :contact

  resources :mailer

  resources :productos

  resources :tipo_productos

  resources :skaters

  resources :comment_posts

  resources :comment_photos

  resources :posts do
    collection do
      get :inicio
    end
  end

  resources :photos

  resources :albums

  devise_for :users

  resources :admin do
    collection do
      get :banner
      get :header
      get :footer
      get :activar_indumentaria
      get :desactivar_indumentaria
      get :crear_valor_indumentaria
      get :creare
      get :newsletterform
      post :contact_email_signed_in
      post :contact_email
    end
  end

  resources :welcome do
    collection do
      get :admin
    end
  end

  match "dispatch_email", to: "admin#dispatch_email", via: 'post'

  root 'welcome#admin'

  

end

sudapp-master/app/models/album.rb
class Album < ActiveRecord::Base

	has_many :photos, :dependent => :destroy
	
	validates_presence_of :album_title

end

sudapp-master/app/models/amigo.rb
class Amigo < ActiveRecord::Base
end

sudapp-master/app/models/comment_photo.rb
class CommentPhoto < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

sudapp-master/app/models/comment_post.rb
class CommentPost < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

sudapp-master/app/models/image.rb
class Image < ActiveRecord::Base
	has_attached_file :photo
end

sudapp-master/app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :user
  belongs_to :producto
end

sudapp-master/app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :album
  
  has_many :comment_photos, :dependent => :destroy

  has_attached_file :photo


  validates_attachment_presence :photo
  validates_presence_of  :photo_title

  
end

sudapp-master/app/models/photo_post.rb
class PhotoPost < ActiveRecord::Base
  belongs_to :post
  has_attached_file :photo
end

sudapp-master/app/models/photo_skater.rb
class PhotoSkater < ActiveRecord::Base
  belongs_to :skater
  has_attached_file :photo
end

sudapp-master/app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comment_posts, :dependent => :destroy

	has_many :photo_posts, :dependent => :destroy

	has_many :video_posts, :dependent => :destroy

	has_attached_file :post_photo


    validates_attachment_presence :post_photo
    validates_presence_of  :post_title
    validates_presence_of :post_body

end

sudapp-master/app/models/producto.rb
class Producto < ActiveRecord::Base

  belongs_to :tipo_producto

  has_many :pedidos, :dependent => :destroy

  has_attached_file :foto_producto

  validates_presence_of :precio
  validates_presence_of :tipo_producto
  validates_presence_of :foto_producto
  validates_presence_of :talles_producto
  validates_presence_of :nombre_producto


end

sudapp-master/app/models/skater.rb
class Skater < ActiveRecord::Base

	has_many :photo_skaters, :dependent => :destroy

	has_many :video_skaters, :dependent => :destroy

	has_attached_file :skater_photo


    validates_attachment_presence :skater_photo
    validates_presence_of  :skater_name
    validates_presence_of :skater_body
    
end

sudapp-master/app/models/tipo_producto.rb
class TipoProducto < ActiveRecord::Base

    has_many :productos, :dependent => :destroy
    
	validates_presence_of :nombre_tipo_producto

end

sudapp-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :comment_photos, :dependent => :destroy

  has_many :comment_posts, :dependent => :destroy
  
  has_many :pedidos, :dependent => :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


        validates :username, :presence => true
        validates :username, :uniqueness => true
        validates :username, length: { maximum: 16 }
        validates :username, length: { minimum: 3 }
        validates :password, length: { maximum: 25 }
        validates :password, length: { minimum: 6 }


end

sudapp-master/app/models/video.rb
class Video < ActiveRecord::Base

validates_presence_of :video_title
validates_presence_of :video_url

end

sudapp-master/app/models/video_post.rb
class VideoPost < ActiveRecord::Base
  belongs_to :post
end

sudapp-master/app/models/video_skater.rb
class VideoSkater < ActiveRecord::Base
  belongs_to :skater
end

sudapp-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json

  def inicio
    @post = Post.find(params[:id])
    Post.all.each do |p|
    if p.id == @post.id
      p.update_attributes(:inicio => 1)
    else
      p.update_attributes(:inicio => 0)
    end 
    end 
    redirect_to posts_path
  end

  def index
    @posts = Post.all(:order => 'created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment_post = CommentPost.new
    @allposts = params[:allposts].to_i

    if @allposts == 0
      @comments = CommentPost.all.last(7).sort { |a,b| b.created_at <=> a.created_at }
    else
      @comments = CommentPost.find(:all).sort { |a,b| b.created_at <=> a.created_at }
    end
  end

  # GET /posts/new
  def new
    admin_check
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    admin_check
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'La nota fue creada exitosamente.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'La nota fue editada exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to :controller => "/posts", :action => "index"}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
  
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post_title, :post_body, :post_photo, :post_autor, :post_photographer)
    end
end

sudapp-master/app/helpers/admin_helper.rb
module AdminHelper
end

sudapp-master/app/helpers/albums_helper.rb
module AlbumsHelper
end

sudapp-master/app/helpers/amigos_helper.rb
module AmigosHelper
end

sudapp-master/app/helpers/images_helper.rb
module ImagesHelper
end

sudapp-master/app/helpers/posts_helper.rb
module PostsHelper
end

sudapp-master/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Titulo" %>
    <%= f.text_field :post_title %>
  </div>
   <div class="field">
    <%= f.label "Autor" %>
    <%= f.text_field :post_autor %>
  </div>

    <div class="field">
    <%= f.label "Foto Principal" %>
    <%= f.file_field :post_photo %>
  </div>

   <div class="field">
    <%= f.label "Foto sacada por:" %>
    <%= f.text_field :post_photographer %>
  </div>


  <div class="field">
    <%= f.label "Contenido" %>
    <%= f.text_area :post_body %>

  </div>

  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

sudapp-master/app/views/posts/edit.html.erb
<h1 style = "color:#B28D8D;">Editar nota</h1>
<br>

<%= render 'form' %>


<%= link_to '→ Volver al administrador', :controller => "/admin" %>

sudapp-master/app/views/posts/index.html.erb
<div class="secciones">N O T A S</div>
<p></p>
<!--<p><div class="fuente-cuatro"><strong>NOTAS</strong></div></p>-->
<% if current_user.try(:admin?)%>
<%= link_to 'Agregar una nueva nota', new_post_path %>
<% end %>
<p></p>
    <% @posts.each do |post| %>
     
        <div class="my-div-bottom"><%= link_to post.post_title.upcase,post_path(:id => post.id, :allposts => 0),:class => "fuente-tres" %></div>
        <% if current_user.try(:admin?)%>
        |<%= link_to ' Editar', edit_post_path(post) %> |
        <%= link_to ' Eliminar', post, method: :delete, data: { confirm: 'Esta seguro que desea eliminar la noticia?' } %></td> |
        <%= link_to 'Asignar al inicio', :controller => '/posts', :action => 'inicio', :id => post.id %> |
		<%= link_to 'Agregar fotos a la nota', :controller => '/photo_posts', :action => 'new', :post_id => post.id, :post_title => post.post_title %> |
		<%= link_to 'Agregar video a la nota', :controller => '/video_posts', :action => 'new', :post_id => post.id, :post_title => post.post_title %> |

   
      <% end %><p></p>
    <% end %>
<br>

sudapp-master/app/views/posts/new.html.erb
<h1 style = "color:#B28D8D;">Agregar nota</h1>
<br>

<%= render 'form' %>

<%= link_to '→ Volver al administrador', :controller => "/admin" %>

sudapp-master/app/views/posts/show.html.erb
<% if current_user.try(:admin?)%>
|<%= link_to ' Editar', edit_post_path(@post) %> |
<%= link_to ' Eliminar',@post, method: :delete, data: { confirm: 'Esta seguro que desea eliminar la noticia?' } %> |
<%= link_to 'Asignar al inicio', :controller => '/posts', :action => 'inicio', :id => @post.id %> |
        <%= link_to 'Asignar al inicio', :controller => '/posts', :action => 'inicio', :id => @post.id %> | <br>
    | <%= link_to 'Agregar fotos a la nota', :controller => '/photo_posts', :action => 'new', :post_id => @post.id, :post_title => @post.post_title %> |
    <%= link_to 'Agregar video a la nota', :controller => '/video_posts', :action => 'new', :post_id => @post.id, :post_title => @post.post_title %> |
    <p></p>
<% end %>

<div class = "secciones" style = "font-size:200%"><%= @post.post_title.upcase %></div><br>

<% if @post.post_autor.nil?  %>
<% else %>
<% if @post.post_autor.gsub(/\s+/, "").empty? %>
<% else %>
<div style="background-color:#151515; padding: 10px 10px 10px 15px"><div class="fuente-tres" style ="color:#866A6A;">NOTA : <%= @post.post_autor.upcase %></div></div>

<% end %>
<% end %>


 <%= image_tag @post.post_photo.url %>


<% if @post.post_photographer.nil?  %>
<% else %>
<% if @post.post_photographer.gsub(/\s+/, "").empty? %>
<% else %>
<div style="background-color:#151515; padding: 10px 10px 10px 15px"><div class="fuente-tres" style ="color:#866A6A;">FOTO : <%= @post.post_photographer.upcase%></div></div>
<% end %>
<% end %>


<p >
  <%= simple_format(@post.post_body, :style => "color:#A4A4A4;font-family: 'Carrois Gothic SC', sans-serif;") %>
</p>

  <hr>

<% 
    @tienefoto
    Post.all.each do |post| 
         PhotoPost.all.each do |foto| 
             if foto.post == post 
                  @tienefoto = 1 
                     break 
             else 
                  @tienefoto = 0 
             end 
         end 
         end

        @tienevideo
    Post.all.each do |post| 
         VideoPost.all.each do |video| 
             if video.post == post 
                  @tienevideo = 1 
                     break 
             else 
                  @tienevideo = 0 
             end 
         end 
         end

         %>


<% if @tienefoto == 1 %>


<div style="border-bottom: solid 1px #1C1B1B">
 <ul class="small-block-grid-3 my-grid" >
 
   <% PhotoPost.all.each do |photo| %>
   <% @url = "background-image: url("+photo.photo.path+");"%>
        <% if photo.post_id == @post.id %>
              <li>
              <div ><%=link_to (photo_post_path(:id => photo.id, :allphotos => 0)){image_tag photo.photo.url, :class => "galeria"}%></div>
              <% if current_user.try(:admin?) %>
              <br>
                | <%= link_to 'Editar', (edit_photo_post_path(:id => photo.id, :post_id => @post.id, :post_title => @post.post_title)) %> |
                <%= link_to 'Eliminar', photo, method: :delete, data: { confirm: 'Esta seguro que desea eliminar la foto?' } %> |
              <% end %>
               </li>
        <% end %>
   <% end %>
 </ul>
</div>

 <% end %>

 <% if @tienevideo == 1 && @tienefoto == 1%>
 <br>
 <% end %>
 <% if @tienevideo == 1 %>

 <ul class="small-block-grid-1 my-grid">

 <%
        VideoPost.all.each do |video|
        if video.post_id == @post.id %>
        <% @video = video %>

      
        <% if @video.video_post_url.include? "youtube.com"
        @numero = @video.video_post_url.partition("=").last
        @video_code = '<iframe width=100% height=400px src="//www.youtube.com/embed/'+@numero+'" frameborder="0" allowfullscreen></iframe>'
        end %>
        <% if @video.video_post_url.include? "vimeo.com" 
         @numero = @video.video_post_url.partition(".com/").last
         @video_code = '<iframe width=100% height=400px  src="//player.vimeo.com/video/'+@numero+'" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
        end %>
        <li ><div><div class = "secciones" style = "font-size:200%"><%= link_to video.video_post_title.upcase, video, :video_id => video.id %></div>
           <% if current_user.try(:admin?) %>
           <br>
                | <%= link_to 'Editar', (edit_video_post_path(:id => video.id, :post_id => @post.id, :post_title => @post.post_title)) %> |
                <%= link_to 'Eliminar', video, method: :delete, data: { confirm: 'Esta seguro que desea eliminar la foto?' } %> |
              <% end %> 
              </div>
        </li>

        <li><%= @video_code.html_safe %></li>
        
      <% end %>
    <% end%>
</ul>  
<% else %>
<br>
<% end %>

<% if user_signed_in? %>
<%= form_for @comment_post do |f| %>
  <div class="field">
    <%= f.label "DEJA TU COMENTARIO" ,:class => "fuente-tres" %>
    <%= f.text_area :content ,:class => "back-text-area-field" %>
    <%= f.hidden_field :post_id, :value => @post.id %>
    <%= f.hidden_field :user_id, :value => current_user.try(:id) %>
  </div>

  <div class="actions">
    <%= f.submit " Comentar " %>
  </div>
 
  <% end %>
  <% else %>
  
  <div class="para-comentar">P A R A &nbsp P O D E R &nbsp C O M E N T A R &nbsp D E B E S &nbsp I N I C I A R &nbsp S E S I O N .</div>
  <% end %>


    <% 
    @tienecomentario
    Post.all.each do |post| 
         CommentPost.all.each do |comentario| 
             if comentario.post == post 
                  @tienecomentario = 1 
                     break 
             else 
                  @tienecomentario = 0 
             end 
         end 
         end
         %>

<% if @tienecomentario == 1 %> 

<% if @allposts == 1 %>
<p><div class = "secciones" style = "font-size:200%">COMENTARIOS:</div></p>
<% else %>
<p><div class = "secciones" style = "font-size:200%">ULTIMOS COMENTARIOS:</div></p>
<% end %>
<hr>
<% @comments.each do |comment| %>
  <% if comment.post_id == @post.id %>
      <div class="fuente-tres" style="color:#49aec3"><strong><%= comment.user.username%> :</strong>
      <% if current_user.try(:admin?) || current_user == comment.user %>
      <%= link_to 'eliminar', comment, method: :delete, data: { confirm: 'Esta seguro que desea eliminar el comentario?' } %>
        <% end %> </div>

        <div><%= simple_format(comment.content,  :style => "color:#A4A4A4;font-family: 'Carrois Gothic SC', sans-serif;") %></div>
        
  <% end %> 
<% end %>
<hr>
<% if @allposts == 0 %>
<div><%= link_to "→ MOSTRAR TODOS LOS COMENTARIOS", post_path(:id => @post.id, :allposts => 1),:class => "link-azul" %></div>
<% end %>
<% if @allposts == 1 %>
<div><%= link_to "→ MOSTRAR SOLO LOS ULTIMOS COMENTARIOS.", post_path(:id => @post.id, :allposts => 0),:class => "link-azul" %></div>
<% end %>

<% else %>
<p><div class = "secciones" style = "font-size:200%">LA NOTA TODAVIA NO TIENE COMENTARIOS, SE EL PRIMERO!</div></p>
<% end %>