sudapp-master/config/routes.rb
Appl::Application.routes.draw do

  resources :images

  resources :amigos

  resources :video_skaters

  resources :photo_skaters do
    collection do
      get :new
    end
  end

  resources :photo_skaters do
    collection do
      get :new
    end
  end

  resources :video_posts do
    collection do
      get :new
    end
  end

  resources :photo_posts do
    collection do
      get :new
    end
  end

  resources :pedidos do
    collection do
      get :pedidos_user
    end
  end

  resources :videos do
    collection do
      get :inicio
    end
  end

  resources :contact

  resources :mailer

  resources :productos

  resources :tipo_productos

  resources :skaters

  resources :comment_posts

  resources :comment_photos

  resources :posts do
    collection do
      get :inicio
    end
  end

  resources :photos

  resources :albums

  devise_for :users

  resources :admin do
    collection do
      get :banner
      get :header
      get :footer
      get :activar_indumentaria
      get :desactivar_indumentaria
      get :crear_valor_indumentaria
      get :creare
      get :newsletterform
      post :contact_email_signed_in
      post :contact_email
    end
  end

  resources :welcome do
    collection do
      get :admin
    end
  end

  match "dispatch_email", to: "admin#dispatch_email", via: 'post'

  root 'welcome#admin'

  

end

sudapp-master/app/models/album.rb
class Album < ActiveRecord::Base

	has_many :photos, :dependent => :destroy
	
	validates_presence_of :album_title

end

sudapp-master/app/models/amigo.rb
class Amigo < ActiveRecord::Base
end

sudapp-master/app/models/comment_photo.rb
class CommentPhoto < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

sudapp-master/app/models/comment_post.rb
class CommentPost < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

sudapp-master/app/models/image.rb
class Image < ActiveRecord::Base
	has_attached_file :photo
end

sudapp-master/app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :user
  belongs_to :producto
end

sudapp-master/app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :album
  
  has_many :comment_photos, :dependent => :destroy

  has_attached_file :photo


  validates_attachment_presence :photo
  validates_presence_of  :photo_title

  
end

sudapp-master/app/models/photo_post.rb
class PhotoPost < ActiveRecord::Base
  belongs_to :post
  has_attached_file :photo
end

sudapp-master/app/models/photo_skater.rb
class PhotoSkater < ActiveRecord::Base
  belongs_to :skater
  has_attached_file :photo
end

sudapp-master/app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comment_posts, :dependent => :destroy

	has_many :photo_posts, :dependent => :destroy

	has_many :video_posts, :dependent => :destroy

	has_attached_file :post_photo


    validates_attachment_presence :post_photo
    validates_presence_of  :post_title
    validates_presence_of :post_body

end

sudapp-master/app/models/producto.rb
class Producto < ActiveRecord::Base

  belongs_to :tipo_producto

  has_many :pedidos, :dependent => :destroy

  has_attached_file :foto_producto

  validates_presence_of :precio
  validates_presence_of :tipo_producto
  validates_presence_of :foto_producto
  validates_presence_of :talles_producto
  validates_presence_of :nombre_producto


end

sudapp-master/app/models/skater.rb
class Skater < ActiveRecord::Base

	has_many :photo_skaters, :dependent => :destroy

	has_many :video_skaters, :dependent => :destroy

	has_attached_file :skater_photo


    validates_attachment_presence :skater_photo
    validates_presence_of  :skater_name
    validates_presence_of :skater_body
    
end

sudapp-master/app/models/tipo_producto.rb
class TipoProducto < ActiveRecord::Base

    has_many :productos, :dependent => :destroy
    
	validates_presence_of :nombre_tipo_producto

end

sudapp-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :comment_photos, :dependent => :destroy

  has_many :comment_posts, :dependent => :destroy
  
  has_many :pedidos, :dependent => :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


        validates :username, :presence => true
        validates :username, :uniqueness => true
        validates :username, length: { maximum: 16 }
        validates :username, length: { minimum: 3 }
        validates :password, length: { maximum: 25 }
        validates :password, length: { minimum: 6 }


end

sudapp-master/app/models/video.rb
class Video < ActiveRecord::Base

validates_presence_of :video_title
validates_presence_of :video_url

end

sudapp-master/app/models/video_post.rb
class VideoPost < ActiveRecord::Base
  belongs_to :post
end

sudapp-master/app/models/video_skater.rb
class VideoSkater < ActiveRecord::Base
  belongs_to :skater
end

sudapp-master/app/controllers/comment_photos_controller.rb
class CommentPhotosController < ApplicationController
  before_action :set_comment_photo, only: [:show, :edit, :update, :destroy]

  # GET /comment_photos
  # GET /comment_photos.json
  def index
    
    @comment_photos = CommentPhoto.all
  end

  # GET /comment_photos/1
  # GET /comment_photos/1.json
  def show
    inaccesible
    @comment_photo = CommentPhoto.new
  end


  # GET /comment_photos/new
  def new
    @comment_photo = CommentPhoto.new
  end

  # GET /comment_photos/1/edit
  def edit
    inaccesible
  end

  # POST /comment_photos
  # POST /comment_photos.json
  def create
    @comment_photo = CommentPhoto.new(comment_photo_params)

    respond_to do |format|
      if @comment_photo.save
        @id = @comment_photo.photo.id.to_s
        @ruta = "/photos/"+@id
        format.html { redirect_to @ruta, notice: 'Ha comentado exitosamente.' }
        format.json { render action: 'show', status: :created, location: @comment_photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comment_photos/1
  # PATCH/PUT /comment_photos/1.json
  def update
    respond_to do |format|
      if @comment_photo.update(comment_photo_params)
        format.html { redirect_to @comment_photo, notice: 'Comment photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comment_photos/1
  # DELETE /comment_photos/1.json
  def destroy
    @comment_photo.destroy
    respond_to do |format|
      format.html { redirect_to comment_photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment_photo
      @comment_photo = CommentPhoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_photo_params
      params.require(:comment_photo).permit(:content, :photo_id, :user_id)
    end

end

sudapp-master/app/helpers/admin_helper.rb
module AdminHelper
end

sudapp-master/app/helpers/albums_helper.rb
module AlbumsHelper
end

sudapp-master/app/helpers/amigos_helper.rb
module AmigosHelper
end

sudapp-master/app/helpers/comment_photos_helper.rb
module CommentPhotosHelper
end

sudapp-master/app/helpers/posts_helper.rb
module PostsHelper
end

sudapp-master/app/views/comment_photos/_form.html.erb
<%= form_for(@comment_photo) do |f| %>
  <% if @comment_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment_photo.errors.count, "error") %> prohibited this comment_photo from being saved:</h2>

      <ul>
      <% @comment_photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sudapp-master/app/views/comment_photos/edit.html.erb
<h1>Editing comment_photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment_photo %> |
<%= link_to 'Back', comment_photos_path %>

sudapp-master/app/views/comment_photos/index.html.erb
<h1>Listing comment_photos</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Photo</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comment_photos.each do |comment_photo| %>
      <tr>
        <td><%= comment_photo.content %></td>
        <td><%= comment_photo.photo %></td>
        <td><%= comment_photo.user %></td>
        <td><%= link_to 'Show', comment_photo %></td>
        <td><%= link_to 'Edit', edit_comment_photo_path(comment_photo) %></td>
        <td><%= link_to 'Destroy', comment_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment photo', new_comment_photo_path %>

sudapp-master/app/views/comment_photos/new.html.erb
<h1>New comment_photo</h1>

<%= render 'form' %>

<%= link_to 'Back', comment_photos_path %>

sudapp-master/app/views/comment_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment_photo.content %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @comment_photo.photo %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment_photo.user %>
</p>

<%= link_to 'Edit', edit_comment_photo_path(@comment_photo) %> |
<%= link_to 'Back', comment_photos_path %>